version: '3.8'

services:
  db:
    image: postgres:14
    container_name: db
    ports:
      - "5432:5432"
    volumes:
      - ./db/pgdata:/var/lib/postgresql/data
    env_file: .env  # Ensure the .env file is loaded correctly
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}  # Ensure the database is set to 'inha_facility'
      TZ: Asia/Seoul
    networks:
      - backend
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 3s
      retries: 5

  backend:
    build: ./backend
    container_name: backend
    command: uvicorn main:app --reload --host 0.0.0.0 --port 8000
    volumes:
      - ./backend/src:/usr/src/app
    ports:
      - "8000:8000"
    env_file: .env  # Ensure this file contains the proper environment variables for DB connection
    networks:
      - backend
    depends_on:
      db:
        condition: service_healthy

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "8080:80"
    networks:
      - backend
    restart: always

networks:
  backend:
