version: '3.8'

services:
  backend:
    build: ./backend
    container_name: backend
    command: uvicorn main:app --reload --host 0.0.0.0 --port 8000
    volumes:
      - ./backend/src:/usr/src/app
    ports:
      - "8000:8000"
    env_file: .env  # Ensure this file contains the proper environment variables for DB connection
    networks:
      - backend

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "8080:80"
    networks:
      - backend
    restart: always

networks:
  backend:
