version: '3.8'

services:
  backend:
    build: ./backend
    container_name: backend
    command: uvicorn main:app --reload --host 0.0.0.0 --port 8000
    volumes:
      - ./backend/src:/usr/src/app
    ports:
      - "8000:8000"
    env_file: .env
    networks:
      - backend

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "8080:80"  # Nginx serves on port 80 inside container
    networks:
      - backend
    depends_on:
      - backend
    restart: always

networks:
  backend:
