facilities:
    대강당: "https://www.inha.ac.kr/kr/1080/subview.do?&enc=Zm5jdDF8QEB8JTJGZmFjaWxpdHklMkZrciUyRmxpc3QuZG8lM0ZzaXRlSWQlM0RrciUyNmNvZGVFJTNERTElMjY="
    중강당: "https://www.inha.ac.kr/kr/1080/subview.do?&enc=Zm5jdDF8QEB8JTJGZmFjaWxpdHklMkZrciUyRmxpc3QuZG8lM0ZzaXRlSWQlM0RrciUyNmNvZGVFJTNERjElMjY="
    소강당: "https://www.inha.ac.kr/kr/1080/subview.do?&enc=Zm5jdDF8QEB8JTJGZmFjaWxpdHklMkZrciUyRmxpc3QuZG8lM0ZzaXRlSWQlM0RrciUyNmNvZGVFJTNERzElMjY="
    5남소강당: "https://www.inha.ac.kr/kr/1080/subview.do?&enc=Zm5jdDF8QEB8JTJGZmFjaWxpdHklMkZrciUyRmxpc3QuZG8lM0ZzaXRlSWQlM0RrciUyNmNvZGVFJTNESDElMjY="
