facilities:
    daegangdang: "https://www.inha.ac.kr/kr/1080/subview.do?&enc=Zm5jdDF8QEB8JTJGZmFjaWxpdHklMkZrciUyRmxpc3QuZG8lM0ZzaXRlSWQlM0RrciUyNmNvZGVFJTNERTElMjY="
    junggangdang: "https://www.inha.ac.kr/kr/1080/subview.do?&enc=Zm5jdDF8QEB8JTJGZmFjaWxpdHklMkZrciUyRmxpc3QuZG8lM0ZzaXRlSWQlM0RrciUyNmNvZGVFJTNERjElMjY="
    sogangdang: "https://www.inha.ac.kr/kr/1080/subview.do?&enc=Zm5jdDF8QEB8JTJGZmFjaWxpdHklMkZrciUyRmxpc3QuZG8lM0ZzaXRlSWQlM0RrciUyNmNvZGVFJTNERzElMjY="
    5nam_sogangdang: "https://www.inha.ac.kr/kr/1080/subview.do?&enc=Zm5jdDF8QEB8JTJGZmFjaWxpdHklMkZrciUyRmxpc3QuZG8lM0ZzaXRlSWQlM0RrciUyNmNvZGVFJTNESDElMjY="
